#restricts pods to 200m cpu/1gi RAM

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerLimits
metadata:
  name: container-limits
spec:
  match:
    excludedNamespaces: ["kube-system"]
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod", "Deployment"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
