apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge23-attacker
spec:
  selector:
    matchLabels:
      app: challenge23-attacker
  replicas: 1 # tells deployment to run 3 pods matching the template
  minReadySeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: challenge23-attacker
    spec:
      containers:
      - name: challenge23
        image: samgabrail/networktools
        imagePullPolicy: Always
