
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowlistedRegistry
metadata:
  name: allowlisted-registry
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod", "Deployment"]
  parameters:
    registries:
      - docker.io
