apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge23
  namespace: admin
spec:
  selector:
    matchLabels:
      app: challenge23
  replicas: 1 # tells deployment to run 3 pods matching the template
  minReadySeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: challenge23
    spec:
      containers:
      - name: challenge23
        image: deadrobots/k8_ctf:challenge23
        ports:
        - containerPort: 27017
        - containerPort: 28017
        imagePullPolicy: Always