apiVersion: v1
kind: Service
metadata:
  name: challenge13
  labels:
    app: challenge13
spec:
  type: LoadBalancer
  selector:
    app: challenge13
  ports:
  - port: 80
    targetPort: 80
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge13-deployment
spec:
  selector:
    matchLabels:
      app: challenge13
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: challenge13
    spec:
      containers:
      - name: challenge13
        image: deadrobots/k8_ctf:challenge13
        ports:
        - containerPort: 80
        imagePullPolicy: Always