apiVersion: v1
kind: Service
metadata:
  name: challenge15-lb
  labels:
    app: challenge15
spec:
  type: LoadBalancer
  selector:
    app: challenge15
  ports:
  - port: 80
    targetPort: 80
 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge15
spec:
  selector:
    matchLabels:
      app: challenge15
  replicas: 6 # tells deployment to run 3 pods matching the template
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: challenge15
    spec:
      containers:
      - name: challenge15
        image: deadrobots/k8_ctf:challenge15
        ports:
        - containerPort: 80
        imagePullPolicy: Always

