apiVersion: v1
kind: Service
metadata:
  name: challenge18-lb
  labels:
    app: challenge18
spec:
  type: LoadBalancer
  selector:
    app:  challenge18
  ports:
  - port: 80
    targetPort: 3000
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge18
spec:
  selector:
    matchLabels:
      app: challenge18
  replicas: 3 # tells deployment to run 3 pods matching the template
  minReadySeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: challenge18
    spec:
      containers:
      - name: challenge18
        image: deadrobots/k8_ctf:challenge18
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodbsecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodbsecret
              key: password
