apiVersion: v1
kind: Service
metadata:
  name: node-svc
  labels:
    app: challenge12
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: challenge12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge12-deployment
spec:
  selector:
    matchLabels:
      app: challenge12
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: challenge12
    spec:
      containers:
      - name: challenge12
        image: deadrobots/k8_ctf:challenge12
        ports:
        - containerPort: 8080
        imagePullPolicy: Always